//! Patient-compartment rules generated by the R6 search registry.
//!
//! The R6 registry exposes a `patient` Reference search parameter on every
//! directly executable Patient-compartment resource.  Reference extraction
//! records that code, making this list auditable without duplicating paths.

use crate::search_params::{SearchParamType, search_params_for};

pub fn is_direct_patient_compartment_type(resource_type: &str) -> bool {
    search_params_for(resource_type)
        .iter()
        .any(|param| param.code == "patient" && param.param_type == SearchParamType::Reference)
}

#[cfg(test)]
mod tests {
    use super::is_direct_patient_compartment_type;

    #[test]
    fn pins_representative_r6_direct_rules() {
        for resource_type in [
            "AllergyIntolerance",
            "Condition",
            "Encounter",
            "MedicationRequest",
            "Observation",
            "Procedure",
        ] {
            assert!(
                is_direct_patient_compartment_type(resource_type),
                "{resource_type}"
            );
        }
        assert!(!is_direct_patient_compartment_type("Organization"));
        let direct_count = crate::search_params::RESOURCE_TYPES
            .iter()
            .filter(|resource_type| is_direct_patient_compartment_type(resource_type))
            .count();
        assert_eq!(direct_count, 62, "R6 direct compartment coverage changed");
    }
}
