apiVersion: v2
name: nissefhir
description: Helm chart for deploying the NisseFHIR server with CloudNativePG.
type: application
version: 0.1.3
appVersion: "0.1.3"
keywords:
  - fhir
  - healthcare
  - hl7
  - rust
  - postgresql
  - cloudnativepg
